---
application:
  name: "daisyxmusic"
  project: "TELEGRAM-OP"
  organization: "QoveryCommunity"
routers:
- name: "main-daisyxmusic"
  routes:
  - application_name: "daisyxmusic"
    paths:
    - "/*"
